version: 1

merge:
  ignore:
    labels: ["do not merge", "do not merge/wip"]
  method: squash
  options:
    squash:
      body: summarize_commits
  delete_after_merge: true
  allow_merge_with_no_checks: false