#!/bin/bash

set -ex

if [[ -d "out" ]]; then
  rm -rf out
fi

binaries=(envsubst api)

for binary in "${binaries[@]}"; do
  CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o out/$binary cmd/$binary/main.go
done