#!/bin/bash

set -ex

if [[ -d "out" ]]; then
  rm -rf out
fi

binaries=(envsubst api)

for binary in "${binaries[@]}"; do
  CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o out/$binary cmd/$binary/main.go
done

static_files=(boundaries.json init.sh config.yaml.example)
static_dirs=(static docs)

for file in "${static_files[@]}"; do
  cp $file out/$file
done

for dir in "${static_dirs[@]}"; do
  cp -Rp $dir out/$dir
done