#!/bin/bash

set -x

wget https://github.com/swaggo/swag/releases/download/v1.8.3/swag_1.8.3_Linux_x86_64.tar.gz -O /tmp/swag.tar.gz
mkdir /tmp/swag || true
tar -xzf /tmp/swag.tar.gz -C /tmp/swag
/tmp/swag/swag init --parseDependency --parseInternal --parseDepth 3 --generalInfo cmd/api/main.go
if [[ $? -ne 0 ]]; then
  rm -rf /tmp/swag
  echo "Failed to generate swagger documentation"
  exit 1
fi
rm -rf /tmp/swag