name: Build and Deploy
on:
  push:
    branches:
      - 'dev'
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout Repo
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.2
    - name: Run tests
      run: make test
    - name: Test docs
      run: make docs
  build:
    name: Build Image
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
      name: Checkout Repo
    - name: Set sha_short
      id: vars
      run: |-
        echo "sha_short=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
        # Set default branch name for PRs, as we still want to test build an image on PRs
        # but we have no branch to set a tag for.
        branch="test"
        if [[ "$GITHUB_REF" == "refs/heads/"* ]]; then
          branch="${GITHUB_REF#refs/heads/}"
        fi
        echo "branch=${branch}" >> $GITHUB_ENV
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Install go dependencies
      run: go get -v ./...
    - name: Build Docs
      run: make docs
    - name: Build Binaries
      run: make build
    - name: Build Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/api:${{ env.branch }} -t ${{ secrets.DOCKER_USERNAME }}/api:${{ env.sha_short }} .
    - name: Push Image
      if: ${{ github.event_name == 'push' }}
      run: docker push --all-tags ${{ secrets.DOCKER_USERNAME }}/api
  deploy-kzdv:
    name: Update KZDV GitOps Repo
    runs-on: ubuntu-latest
    needs: build
    if : ${{ github.event_name == 'push' && contains(fromJson('["refs/heads/dev", "refs/heads/main"]'), github.ref) }}

    steps:
    - name: Checkout KZDV Gitops Repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PIPELINE_PAT }}
        repository: 'kzdv/devops'
        path: gitops
    - name: Configure git
      run: |-
        cd $GITHUB_WORKSPACE/gitops/k8s/gitops
        git config user.name "${{ secrets.GH_PIPELINE_USERNAME }}"
        git config user.email "wm@denartcc.org"
    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "4.4.1"
    - name: Update dev overlay
      if: ${{ github.ref == 'refs/heads/dev' }}
      run: |
        HASH=`echo ${GITHUB_SHA} | cut -c1-7`
        cd $GITHUB_WORKSPACE/gitops/k8s/gitops/overlays/dev
        kustomize edit set image denartcc/api=adhp/api:$HASH
    - name: Update prod overlay
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        HASH=`echo ${GITHUB_SHA} | cut -c1-7`
        cd $GITHUB_WORKSPACE/gitops/k8s/gitops/overlays/prod
        kustomize edit set image denartcc/api=adhp/api:$HASH
    - name: Commit manifests
      run: |
        cd $GITHUB_WORKSPACE/gitops/k8s/gitops
        git add .
        git commit -m "Update manifests for api"
    - name: Push to gitops repo
      run: |
        cd $GITHUB_WORKSPACE/gitops/k8s/gitops
        git push origin master
  deploy-paza:
    name: Update PAZA GitOps Repo
    runs-on: ubuntu-latest
    needs: build
    if : ${{ github.event_name == 'push' && contains(fromJson('["refs/heads/dev", "refs/heads/main"]'), github.ref) }}

    steps:
    - name: Checkout PAZA Gitops Repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAZA_GITOPS_TOKEN }}
        repository: 'vpaza/gitops'
        path: gitops-paza
    - name: Configure git
      run: |-
        cd $GITHUB_WORKSPACE/gitops-paza
        git config user.name "${{ secrets.PAZA_GITOPS_USER }}"
        git config user.email "${{ secrets.PAZA_GITOPS_EMAIL }}"
    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "4.4.1"
    - name: Update dev overlay
      if: ${{ github.ref == 'refs/heads/dev' }}
      run: |
        HASH=`echo ${GITHUB_SHA} | cut -c1-7`
        cd $GITHUB_WORKSPACE/gitops-paza/overlays/dev
        kustomize edit set image denartcc/api=adhp/api:$HASH
    - name: Update prod overlay
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        HASH=`echo ${GITHUB_SHA} | cut -c1-7`
        cd $GITHUB_WORKSPACE/gitops-paza/overlays/prod
        kustomize edit set image denartcc/api=adhp/api:$HASH
    - name: Commit manifests
      run: |
        cd $GITHUB_WORKSPACE/gitops-paza
        git add .
        git commit -m "Update manifests for api"
    - name: Push to gitops repo
      run: |
        cd $GITHUB_WORKSPACE/gitops-paza
        git push origin main

  deploy-phzh:
    name: Update PHZH GitOps Repo
    runs-on: ubuntu-latest
    needs: build
    if : ${{ github.event_name == 'push' && contains(fromJson('["refs/heads/dev", "refs/heads/main"]'), github.ref) }}

    steps:
    - name: Checkout PHZH Gitops Repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAZA_GITOPS_TOKEN }}
        repository: 'vphzh/gitops'
        path: gitops-phzh
    - name: Configure git
      run: |-
        cd $GITHUB_WORKSPACE/gitops-phzh
        git config user.name "${{ secrets.PAZA_GITOPS_USER }}"
        git config user.email "${{ secrets.PAZA_GITOPS_EMAIL }}"
    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "4.4.1"
    - name: Update dev overlay
      if: ${{ github.ref == 'refs/heads/dev' }}
      run: |
        HASH=`echo ${GITHUB_SHA} | cut -c1-7`
        cd $GITHUB_WORKSPACE/gitops-phzh/overlays/dev
        kustomize edit set image denartcc/api=adhp/api:$HASH
    - name: Update prod overlay
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        HASH=`echo ${GITHUB_SHA} | cut -c1-7`
        cd $GITHUB_WORKSPACE/gitops-phzh/overlays/prod
        kustomize edit set image denartcc/api=adhp/api:$HASH
    - name: Commit manifests
      run: |
        cd $GITHUB_WORKSPACE/gitops-phzh
        git add .
        git commit -m "Update manifests for api"
    - name: Push to gitops repo
      run: |
        cd $GITHUB_WORKSPACE/gitops-phzh
        git push origin main
