name: lint

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout Repo
    - name: Run Lint
      run: make lint